version: "3.8"

services:
  bot:
    build: .
    env_file: .env
    restart: always
    container_name: index-bot-container
    image: index-bot-image
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
